/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 drone.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/drone.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0}>
        <group position={[0, -67.41, 251.04]} scale={20.2}>
          <mesh geometry={nodes.node_id119.geometry} material={materials['120']} />
          <mesh geometry={nodes.node_id121.geometry} material={materials['121']} />
          <mesh geometry={nodes.node_id123.geometry} material={materials['122']} />
          <mesh geometry={nodes.node_id125.geometry} material={materials['123']} />
          <mesh geometry={nodes.node_id127.geometry} material={materials['124']} />
          <mesh geometry={nodes.node_id129.geometry} material={materials['125']} />
          <mesh geometry={nodes.node_id131.geometry} material={materials['126']} />
          <mesh geometry={nodes.node_id133.geometry} material={materials['127']} />
          <mesh geometry={nodes.node_id135.geometry} material={materials['128']} />
          <mesh geometry={nodes.node_id137.geometry} material={materials['129']} />
          <mesh geometry={nodes.node_id139.geometry} material={materials['130']} />
          <mesh geometry={nodes.node_id141.geometry} material={materials['131']} />
          <mesh geometry={nodes.node_id143.geometry} material={materials['132']} />
          <mesh geometry={nodes.node_id145.geometry} material={materials['133']} />
          <mesh geometry={nodes.node_id147.geometry} material={materials['134']} />
          <mesh geometry={nodes.node_id149.geometry} material={materials['135']} />
          <mesh geometry={nodes.node_id151.geometry} material={materials['136']} />
          <mesh geometry={nodes.node_id153.geometry} material={materials['137']} />
          <mesh geometry={nodes.node_id155.geometry} material={materials['138']} />
          <mesh geometry={nodes.node_id157.geometry} material={materials['139']} />
          <mesh geometry={nodes.node_id159.geometry} material={materials['140']} />
          <mesh geometry={nodes.node_id161.geometry} material={materials['141']} />
          <mesh geometry={nodes.node_id163.geometry} material={materials['142']} />
          <mesh geometry={nodes.node_id165.geometry} material={materials['143']} />
          <mesh geometry={nodes.node_id167.geometry} material={materials['144']} />
          <mesh geometry={nodes.node_id169.geometry} material={materials['145']} />
          <mesh geometry={nodes.node_id171.geometry} material={materials['146']} />
          <mesh geometry={nodes.node_id173.geometry} material={materials['147']} />
          <mesh geometry={nodes.node_id175.geometry} material={materials['148']} />
          <mesh geometry={nodes.node_id177.geometry} material={materials['149']} />
          <mesh geometry={nodes.node_id179.geometry} material={materials['150']} />
          <mesh geometry={nodes.node_id181.geometry} material={materials['151']} />
          <mesh geometry={nodes.node_id183.geometry} material={materials['152']} />
          <mesh geometry={nodes.node_id185.geometry} material={materials['153']} />
          <mesh geometry={nodes.node_id187.geometry} material={materials['154']} />
          <mesh geometry={nodes.node_id189.geometry} material={materials['155']} />
          <mesh geometry={nodes.node_id191.geometry} material={materials['156']} />
          <mesh geometry={nodes.node_id193.geometry} material={materials['157']} />
          <mesh geometry={nodes.node_id195.geometry} material={materials['158']} />
          <mesh geometry={nodes.node_id197.geometry} material={materials['159']} />
          <mesh geometry={nodes.node_id199.geometry} material={materials['160']} />
          <mesh geometry={nodes.node_id201.geometry} material={materials['161']} />
          <mesh geometry={nodes.node_id203.geometry} material={materials['162']} />
          <mesh geometry={nodes.node_id205.geometry} material={materials['163']} />
          <mesh geometry={nodes.node_id207.geometry} material={materials['164']} />
          <mesh geometry={nodes.node_id209.geometry} material={materials['165']} />
          <mesh geometry={nodes.node_id211.geometry} material={materials['166']} />
          <mesh geometry={nodes.node_id213.geometry} material={materials['167']} />
          <mesh geometry={nodes.node_id215.geometry} material={materials['168']} />
          <mesh geometry={nodes.node_id217.geometry} material={materials['169']} />
          <mesh geometry={nodes.node_id219.geometry} material={materials['170']} />
          <mesh geometry={nodes.node_id221.geometry} material={materials['171']} />
          <mesh geometry={nodes.node_id223.geometry} material={materials['172']} />
          <mesh geometry={nodes.node_id225.geometry} material={materials['173']} />
          <mesh geometry={nodes.node_id227.geometry} material={materials['174']} />
          <mesh geometry={nodes.node_id229.geometry} material={materials['175']} />
          <mesh geometry={nodes.node_id231.geometry} material={materials['176']} />
          <mesh geometry={nodes.node_id233.geometry} material={materials['177']} />
          <mesh geometry={nodes.node_id235.geometry} material={materials['178']} />
          <mesh geometry={nodes.node_id237.geometry} material={materials['179']} />
          <mesh geometry={nodes.node_id239.geometry} material={materials['180']} />
          <mesh geometry={nodes.node_id241.geometry} material={materials['181']} />
          <mesh geometry={nodes.node_id243.geometry} material={materials['182']} />
          <mesh geometry={nodes.node_id245.geometry} material={materials['183']} />
          <mesh geometry={nodes.node_id247.geometry} material={materials['184']} />
          <mesh geometry={nodes.node_id249.geometry} material={materials['185']} />
          <mesh geometry={nodes.node_id251.geometry} material={materials['186']} />
          <mesh geometry={nodes.node_id253.geometry} material={materials['187']} />
          <mesh geometry={nodes.node_id255.geometry} material={materials['188']} />
          <mesh geometry={nodes.node_id257.geometry} material={materials['189']} />
          <mesh geometry={nodes.node_id259.geometry} material={materials['190']} />
          <mesh geometry={nodes.node_id261.geometry} material={materials['191']} />
          <mesh geometry={nodes.node_id263.geometry} material={materials['192']} />
          <mesh geometry={nodes.node_id265.geometry} material={materials['193']} />
          <mesh geometry={nodes.node_id267.geometry} material={materials['194']} />
          <mesh geometry={nodes.node_id269.geometry} material={materials['195']} />
          <mesh geometry={nodes.node_id271.geometry} material={materials['196']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/drone.gltf')
